clientes = {
    # "2": {"nombre": "a todos"},
    # "4": {"nombre": "Matteo"},
    # "5": {"nombre": "Carlos"},
    # "6": {"nombre": "Óscar"},
    "7": {"nombre": "Hozkel"},
    # "10": {"nombre": "Rafael"},
    # "11": {"nombre": "Abraham"},
    # "14FAM": {"nombre": "Manuel y Hugo"},
    # "14PER": {"nombre": "Frida"},
    # "17": {"nombre": "Vayo"},
    # "32": {"nombre": "Don Pedro y Christian"},
    # "35": {"nombre": "Esther"},
    # "43": {"nombre": "Renzo"},
    # "51": {"nombre": "Doris y Jose Ignacio"},
    # "55": {"nombre": "Marcela y César"},
    # "56": {"nombre": "Edwin y Arnold"},
    # "58": {"nombre": "Rocío y Álvaro"},
    # "64": {"nombre": "Ernesto"},
    # "65": {"nombre": "Eduardo"},
    # "71": {"nombre": "Soledad y José"},
    # "72": {"nombre": "a todos"},
    # "74": {"nombre": "Margarita"},
    # "77": {"nombre": "Frida"},
    # "78": {"nombre": "Felipe"},
    # "79": {"nombre": "Rafael"},
    # "80": {"nombre": "Susan"},
    # "81": {"nombre": "Virginia"},
    # "83": {"nombre": "Matteo"},
    # "84": {"nombre": "Javier"},
    # "85": {"nombre": "Emilio"},
    # "86": {"nombre": "Lorenzo"},
    # "87": {"nombre": "Jaime"},
    # "89": {"nombre": "Victor"},
    # "91": {"nombre": "Thalia y Yair"},
    # "92": {"nombre": "Joana y Alex"},
    # "93": {"nombre": "Guil"},
}
