# # clientes = {
#     "2": {"nombre": "a todos", "email": "correo@empresa.com"},
#     "4": {"nombre": "Matteo", "email": "correo@empresa.com"},
#     "5": {"nombre": "Carlos", "email": "correo@empresa.com"},
#     "6": {"nombre": "Óscar", "email": "correo@empresa.com"},
#     "7": {"nombre": "Hozkel", "email": "correo@empresa.com"},
#     "10": {"nombre": "Rafael", "email": "correo@empresa.com"},
#     "11": {"nombre": "Abraham", "email": "correo@empresa.com"},
#     "14FAM": {"nombre": "Manuel y Hugo", "email": "correo@empresa.com"},
#     "14PER": {"nombre": "Frida", "email": "correo@empresa.com"},
#     "17": {"nombre": "Vayo", "email": "correo@empresa.com"},
#     "32": {"nombre": "Don Pedro y Christian", "email": "correo@empresa.com"},
#     "35": {"nombre": "Esther", "email": "correo@empresa.com"},
#     "43": {"nombre": "Renzo", "email": "correo@empresa.com"},
#     "51": {"nombre": "Doris y Jose Ignacio", "email": "correo@empresa.com"},
#     "55": {"nombre": "Marcela y César", "email": "correo@empresa.com"},
#     "56": {"nombre": "Edwin y Arnold", "email": "correo@empresa.com"},
#     "58": {"nombre": "Rocío y Álvaro", "email": "correo@empresa.com"},
#     "64": {"nombre": "Ernesto", "email": "correo@empresa.com"},
#     "65": {"nombre": "Eduardo", "email": "correo@empresa.com"},
#     "71": {"nombre": "Soledad y José", "email": "correo@empresa.com"},
#     "72": {"nombre": "a todos", "email": "correo@empresa.com"},
#     "74": {"nombre": "Margarita", "email": "correo@empresa.com"},
#     "77": {"nombre": "Frida", "email": "correo@empresa.com"},
#     "78": {"nombre": "Felipe", "email": "correo@empresa.com"},
#     "79": {"nombre": "Rafael", "email": "correo@empresa.com"},
#     "80": {"nombre": "Susan", "email": "correo@empresa.com"},
#     "81": {"nombre": "Virginia", "email": "correo@empresa.com"},
#     "83": {"nombre": "Matteo", "email": "correo@empresa.com"},
#     "84": {"nombre": "Javier", "email": "correo@empresa.com"},
#     "85": {"nombre": "Emilio", "email": "correo@empresa.com"},
#     "86": {"nombre": "Lorenzo", "email": "correo@empresa.com"},
#     "87": {"nombre": "Jaime", "email": "correo@empresa.com"},
#     "89": {"nombre": "Victor", "email": "correo@empresa.com"},
#     "91": {"nombre": "Thalia y Yair", "email": "correo@empresa.com"},
#     "92": {"nombre": "Joana y Alex", "email": "correo@empresa.com"},
#     "93": {"nombre": "Guil", "email": "correo@empresa.com"},
# }
clientes = {
    "4": {"nombre": "Matteo", "email": "correo@empresa.com"},
    "5": {"nombre": "Carlos", "email": "correo@empresa.com"},
    "6": {"nombre": "Óscar", "email": "correo@empresa.com"},
    "77": {"nombre": "Frida", "email": "correo@empresa.com"},
}